# Numpy

In [1]:
import numpy as np 

In [2]:
tab = np.array([2,3,4,5,6])

In [3]:
tab

array([2, 3, 4, 5, 6])

In [6]:
tab.ndim

1

In [7]:
tab.shape

(5,)

In [11]:
np.random.seed(100)
np.random.rand(3 , 4)

array([[0.54340494, 0.27836939, 0.42451759, 0.84477613],
       [0.00471886, 0.12156912, 0.67074908, 0.82585276],
       [0.13670659, 0.57509333, 0.89132195, 0.20920212]])

In [27]:
A  = np.linspace(1, 12 , 12).reshape(3,4)
print(A)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [34]:
B  = np.linspace(1, 12 , 12).reshape((3,4))
print(A)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [35]:
AB = np.hstack((A , B))
print(AB)

[[ 1.  2.  3.  4.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  5.  6.  7.  8.]
 [ 9. 10. 11. 12.  9. 10. 11. 12.]]


In [38]:
np.vstack((A ,B))

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [37]:
np.concatenate((A , B) , axis=0)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

# NUMPY Indexing Slicing Masking

In [39]:
A

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [41]:
A[1] # sans un dexieme parametre on considere les lignes

array([5., 6., 7., 8.])

In [43]:
A[0:2 , 0:3]

array([[1., 2., 3.],
       [5., 6., 7.]])

In [45]:
A[0:2] # du coup ici on affiche les lignes 0 a 2 

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [47]:
C =  np.zeros((4 , 4))
C

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
C[1:3 , 1:3] = 10
C

array([[ 0.,  0.,  0.,  0.],
       [ 0., 10., 10.,  0.],
       [ 0., 10., 10.,  0.],
       [ 0.,  0.,  0.,  0.]])

# MATPLOTLIB 

MATPLOTLIB 